permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Weber
  email: 912478560@qq.com
  link: http://wangbobo.top
  github: http://github.com/Weber1993

# 站点信息
title: 王波的博客
description: My personal blog
url: http://wangbobo.top
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: http://wangbobo.top

# disqus 设置
disqus:
  shortname: wangbobo

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
#cates: 
 # - Optimization
  #- LaTeX

# 中文本地化
locals:
  tags: 标签
  newest: 最新文章
  archive: 归档
#theme: jekyll-theme-minimal